<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms> <!-- لازم عشان System Tray (NotifyIcon) -->
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>RamGuard</AssemblyName>
    <RootNamespace>RamGuard</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <LangVersion>latest</LangVersion>
    <Platforms>x64</Platforms>
    <ApplicationIcon>Assets\icon.ico</ApplicationIcon>
  </PropertyGroup>

</Project>
